### PR TITLE
Add .editorconfig for all editors

### PR DESCRIPTION
**Pull request by Luchanso**
This tool helping configure formats like tabs/spaces in all editors

https://editorconfig.org/

### CODE REVIEW

**Comment by Luchanso** [comment]
So, you need this review @qqLyamin, then you need Approve or Reject/Decline this pull request. After approve you can merge

**Comment by Luchanso** [comment]
@BortEngineerDude what you think about group review?

**Comment by BortEngineerDude** [comment]
~I'm curious about other integration, less popular IDEs, i.e. QtCreator?~
NVM, https://github.com/editorconfig/editorconfig-qtcreator

**Comment by BortEngineerDude** [comment]
> This tool helping configure formats like tabs/spaces in all editors
> 
> https://editorconfig.org/
--

~I'm curious about other integration, less popular IDEs, i.e. QtCreator?~
 NVM, https://github.com/editorconfig/editorconfig-qtcreator

**Comment by Luchanso** [comment]
@qqLyamin why you close PR? I want use this solution in Production and improve somethings

**Pull request closed without merging**
